### ISSUE TITLE
AttributeError: 'module' object has no attribute 'register'

### ISSUE THREAD

**Issue by justmytwospence** [jo-tham/org_pandoc_reader#1]
Using Pelican 3.6.6 and Python 3.4.3 I get the following error. (Maybe its Python 3 causing the problem?)

```
Traceback (most recent call last):
  File "/Users/sgb/.virtualenvs/blog/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/Users/sgb/.virtualenvs/blog/lib/python3.4/site-packages/pelican/__init__.py", line 386, in main
    pelican, settings = get_instance(args)
  File "/Users/sgb/.virtualenvs/blog/lib/python3.4/site-packages/pelican/__init__.py", line 380, in get_instance
    return cls(settings), settings
  File "/Users/sgb/.virtualenvs/blog/lib/python3.4/site-packages/pelican/__init__.py", line 57, in __init__
    self.init_plugins()
  File "/Users/sgb/.virtualenvs/blog/lib/python3.4/site-packages/pelican/__init__.py", line 84, in init_plugins
    plugin.register()
AttributeError: 'module' object has no attribute 'register'
```

**Comment by jo-tham** [comment]
sorry @justmytwospence, I missed this notification. Any luck since then?

org_pandoc_reader was set tested on python 3.4 and 3.5, but pelican 3.5.0

looks like 3.6 [changed how plugins register](https://github.com/getpelican/pelican/compare/3.5.0...3.6.0#diff-cac3480049a8bf8863a858f05f9c5fefL138)

If you have time to make a PR for this I'd gladly review. Otherwise, I will put it on my list to update soon.
